### ISSUE TITLE
binder link not working

### ISSUE THREAD

**Issue by scottyhq** [ICESAT-2HackWeek/2020_ICESat-2_Hackweek_Tutorials#5]
Could not resolve ref for gh:ICESAT-2HackWeek/2020_ICESat-2_Hackweek_Tutorials/binder. Double check your URL. GitHub recently changed default branchesfrom "master" to "main".

**Comment by JessicaS11** [comment]
I changed everything over from "master" to "main", but I'm still getting the error. I know you've been doing some updating for upcoming hackweeks. Does the Docker reference `FROM uwhackweeks/icesat2:2020.06.15` still exist?
